#' @title
#' Generate a synthetic data from a stub precursor object
#' 
#' @description
#' `ble()` is an internal function of [`stubble`] that is used to generate 
#' synthetic data from an precursor object that has been generated by [stub].
#' 
#' @param stb the stub object which synthetic data is generated.
#' @param rows the number of elements to generate.
#' @param ctrl a named list of control parameters for generating the synthetic
#' data. See [`stubble_ctrl`].
#' @param ... named individual control parameters, which take precedence over
#' those in the `ctrl` list.
#'
#' @details
#' `ble()` calls an internal S3 generic function, `ble_()`, with built-in
#' methods for the `list` and `data.frame` base R data types, in addition to
#' `data.table` and `tbl_df` data types, where the required _data.table_ and
#' _tibble_ packages are installed.
#' 
#' @return
#' An object of the same class used in [`stub`].
#' 
#' @seealso 
#' [stubble_ctrl]
#' 
#' @examples
#' ble(stub(penguins_ext))
#' ble(stub(penguins_ext), rows = 10)
#' 
#' @concept empirical
#' @concept ecdf
#' @concept sample
#' @concept simulate
#' @concept simulated
#' @concept simulation
#' 
#' @keywords datagen


### ToDo ###
# - Pass all ble_() methods through ble_.list() to avoid code replication.


### ble() ###
#' @export
ble <- function(stb, rows, ctrl = list(), ...){
  
  ### Checks & Data Extraction ###
  dtype <- stb[["dtype"]]
  vars <- stb[["vars"]]
  old_ctrl <- stb[["ctrl"]]
  if (missing(rows)) rows <- vapply(X = vars, FUN = `[[`, FUN.VALUE = numeric(1L), "n")
  method <- vapply(X = lapply(X = vars, FUN = `[[`, "sim"), FUN = `[[`, FUN.VALUE = character(1L), "method")
  
  ## Control Params ## - Got to be a one-liner for this!
  # old_ctrl <- stubble_ctrl(old_ctrl = old_ctrl) # Something like this?
  # ctrl <- stubble_ctrl(old_ctrl = ctrl)
  ctrl <- c(
    ctrl[!{names(ctrl) %in% names(old_ctrl)}],
    ctrl[names(ctrl) %in% names(old_ctrl)],
    old_ctrl[!{names(old_ctrl) %in% names(ctrl)}]
  )
  
  ## Create Index ##
  index <- seq_along(vars)
  
  ## Apply ble_attr() ##
  l <- mapply(
    FUN = ble_attr,
    x = vars,
    elements = rows,
    method = method,
    index = index,
    MoreArgs = list(ctrl = ctrl, ...),
    SIMPLIFY = FALSE,
    USE.NAMES = TRUE
  )
  
  ## Coerce to Correct Output Type ##
  out <- ble_(dtype = dtype, l = l)
  
  ## Output ##
  return(out)
  
}


### ble_() ###
#' @noRd
ble_ <- function(dtype, ...){
  
  ## Define S3 Method ##
  UseMethod("ble_", dtype)
  
}


### ble_.default() ###
#' @export
ble_.default <- function(dtype, ...){
  
  ## Error ##
  .stop_no_method(dtype)
  
}


### ble_.data.frame() ###
#' @export
ble_.data.frame <- function(dtype, l){
  
  ## Coerce to data.frame ##
  out <- as.data.frame(l)
  
  ## Output ##
  return(out)
  
}


### ble_.data.table() ###
#' @export
ble_.data.table <- function(dtype, l){
  
  ## Coerce to data.table ##
  out <- if (getOption("stubble_has_data.table")){
    
    data.table::as.data.table(l)
    
  } else {
    
    # Warning #
    .warning_coercion(dtype)
    
    as.data.frame(l)
    
  }
  
  ## Output ##
  return(out)
  
}


### ble_.list() ###
#' @export
ble_.list <- function(dtype, l){
  
  ## Output ##
  return(l)
  
}


### ble_.tbl_df() ###
#' @export
ble_.tbl_df <- function(dtype, l){
  
  ## Coerce to tbl_df ##
  out <- if (getOption("stubble_has_tibble")){
    
    tibble::as_tibble(l)
    
  } else {
    
    # Warning #
    .warning_coercion(dtype)
    
    as.data.frame(l)
    
  }
  
  ## Output ##
  return(out)
  
}
