#' Create simple simulated data from a tibble
#'
#' `stubblise()` (equivalently, `stubblize()`) generates synthetic (i.e.
#' simulated) data to match the structure of a given tibble. See also
#' [gen_col], which does the work, and [control] for information on
#' user-modifiable parameters.
#'
#' @param tbbl the tibble to emulate. Can have 0 rows.
#' @param rows the number of simulated rows to generate.
#' @param ... control parameters for ranges and valid levels/characters in the
#' synthetic data. See [control].
#'
#' @details One intended use of `stubblise()` is in generating test data for R
#' package development. The function can create very simple synthetic data from
#' most tibbles where columns have standard R vector types. Currently
#' list-columns are not fully supported, and this and any other unsupported
#' types will return a column of `NA`s (for unsupported types, the resulting
#' column of `NA`s will have type `numeric`).
#'
#' Data are randomly generated by sampling uniformly from a numeric or integer
#' range or from a selection of e.g. characters or factor levels. The
#' parameters controlling this sampling can be modified by the user. At
#' present, the same parameters apply to all columns, and there is no attempt
#' to make the synthetic data look anything like the original data in `tbbl`.
#'
#' Note that although `tbbl` can have 0 rows, there is no benefit to passing
#' `stubblise()` an empty tibble. The computation time is not dependent on
#' the number of rows in `tbbl` (thanks to the magic of S3 methods and lazy
#' evaluation).  Computation time does increase, approximately linearly, with
#' the number of columns in `tbbl` and with the number of rows required in the
#' result (`rows`).
#'
#' The function `stubblize()` is a synonym for `stubblise()`.
#'
#' @return A tibble, with the same structure as `tbbl`, but containing random
#' data. Any columns which are not recognised as being of a standard vector
#' type will have `NA` for all rows and the column type will be `numeric`,
#' not the original vector type.
#'
#' @section Sensitive data:
#'
#' By default, outputs from `stubblise()` should contain no sensitive data,
#' *unless the column names and types are themselves sensitive*. Tibble
#' attributes are not preserved by `stubblise()` (they are regenerated by
#' [tibble::as_tibble] from a list of columns generated by [gen_col]).
#'
#' It is possible to leak sensitive data via a "stubblised" tibble if the
#' values of the [control] parameters have been changed and are themselves
#' derived from sensitive data. It is recommended to leave these parameters
#' at their default values in any circumstance that involves sensitive data
#' (e.g. personal data of any sort), or otherwise to ensure that they are set
#' to non-informative values.
#'
#' @examples
#' # A simple examples producing nonsense data
#' syn_iris_0 <- stubblise(iris)
#'
#' # Example with Species factor levels
#' syn_iris_1 <- stubblise(
#'   iris,
#'   fct_lvls = list(levels(iris$Species))
#' )
#'
#' # Example producing data more comparable to the real iris
#' mins <- as.numeric(dplyr::summarise_if(iris, is.numeric, min))
#' maxs <- as.numeric(dplyr::summarise_if(iris, is.numeric, max))
#' lvls <- levels(iris$Species)
#' rows <- dplyr::count(iris, Species)$n
#' syn_iris_2 <- purrr::map2_dfr(
#'   rows, lvls,
#'   ~ stubblise(
#'     iris, rows = .x,
#'     dbl_min = mins, dbl_max = maxs, dbl_round = 1L,
#'     fct_lvls = list(lvls), fct_use_lvls = list(.y)
#'   )
#' )
#'
#' @export
stubblise <- function(tbbl, rows = 10L, ...) {

  tryCatch(
    tbbl <- tibble::as_tibble(tbbl),
    error = function(err) stop("Cannot coerce argument 'tbbl' to tibble"),
    warning = function(warn) warning(warn)
  )

  index <- 1:ncol(tbbl)

  tibble::as_tibble(
    mapply(
      gen_col, tbbl, index,
      MoreArgs = list(elements = rows, ...),
      SIMPLIFY = FALSE,
      USE.NAMES = TRUE
    )
  )

}


#' @rdname stubblise
#' @export
stubblize <- stubblise
